name: majadigi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.2
  dartz: ^0.10.1
  equatable: ^2.0.8
  firebase_auth: ^6.3.0
  flutter_dotenv: ^6.0.1
  go_router: ^17.2.2
  firebase_remote_config: ^6.4.0
  cloud_firestore: ^6.3.0
  flutter_svg: ^2.2.4
  intl: ^0.20.2
  carousel_slider: ^5.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  google_fonts: ^8.1.0
  flutter_launcher_icons: ^0.14.4
  shimmer: ^3.0.0
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  
  deferred-components:
    - name: harga_bahan_pokok
      libraries:
        - lib/deffered_feature/harga_bahan_pokok/presentation/pages/harga_bahan_pokok_page.dart
    - name: ketersediaan_kamar
      libraries:
        - lib/deffered_feature/ketersediaan_kamar/presentation/pages/ketersediaan_kamar_page.dart
    - name: antrean_pasien
      libraries:
        - lib/deffered_feature/antrean_pasien/presentation/pages/antrean_pasien_page.dart
    - name: jadwal_operasi
      libraries:
        - lib/deffered_feature/jadwal_operasi/presentation/pages/jadwal_operasi_page.dart
    - name: destinasi_wisata
      libraries:
        - lib/deffered_feature/destinasi_wisata/presentation/pages/destinasi_wisata_page.dart

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/main_background.png
    - .env
    - lib/core/env/.env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
