// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAasJsYQC3aMbZZdjf1CwcXd3pmcw9JmnE',
    appId: '1:719401642649:web:c9cfffaccc17fb4480e608',
    messagingSenderId: '719401642649',
    projectId: 'majadigi-app',
    authDomain: 'majadigi-app.firebaseapp.com',
    databaseURL: 'https://majadigi-app-default-rtdb.firebaseio.com',
    storageBucket: 'majadigi-app.firebasestorage.app',
    measurementId: 'G-2MKGPGT2SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAtGFxCN8SuDif_9uhphRU6q7LIYZvsQ',
    appId: '1:719401642649:android:585a07fbf8523a6780e608',
    messagingSenderId: '719401642649',
    projectId: 'majadigi-app',
    databaseURL: 'https://majadigi-app-default-rtdb.firebaseio.com',
    storageBucket: 'majadigi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMa-Yw_88YGqhKOoi4RHRWJ5SyupVtMw',
    appId: '1:719401642649:ios:35dc58649aa71f1380e608',
    messagingSenderId: '719401642649',
    projectId: 'majadigi-app',
    databaseURL: 'https://majadigi-app-default-rtdb.firebaseio.com',
    storageBucket: 'majadigi-app.firebasestorage.app',
    iosBundleId: 'com.example.majadigi',
  );

}